title: Jekyll Resume Template
description: A resume template for Jekyll and GitHub Pages sites.
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
resume_avatar: 'true'
resume_name: M.Tariq Aziz
resume_title: Data Analyst / Upcoming Data Scientist
resume_contact_email: ta.aziz221@gmail.com
resume_contact_telephone: 555-7334
resume_contact_address: '742 Evergreen Terrace, Springfield'
resume_header_contact_info: >-
  742 Evergreen Terrace, Springfield â€¢ 555-7334 â€¢
  lisasimpson@youremailaddress.com
display_header_contact_info: 'false'
resume_header_intro: >-
  <p> I am Data Analyst, enrolled in the Springboard Data Science Bootcamp, where I gain knowledge and hands-on experience in Data Science and Machine Learning.
ğŸ‘¯ Iâ€™m always open to interesting conversations and collaboration.
âš¡ Fun fact: I love coffee â˜•
ğŸ¹ My motto is: "Never cease to learn, for life is an endless teacher."</p>
resume_looking_for_work: 'yes'
resume_section_projects: true
resume_section_experience: true
resume_section_education: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
resume_social_links:
  resume_github_url: 'https://github.com/ttariqaziz'
  resume_twitter_url: 'http://twitter.com/jglovier'
  resume_linkedin_url: 'https://www.linkedin.com/in/mtariqaziz'
  resume_website_url: 'http://ttariqaziz.github.io'
  resume_medium_url: 'https://medium.com/@jglovier'
resume_print_social_links: true
resume_theme: default
